/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProduitsSlugRouteImport } from './routes/produits.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/produits': typeof ProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostic'
    | '/blog/$slug'
    | '/produits/$slug'
    | '/blog/'
    | '/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostic'
    | '/blog/$slug'
    | '/produits/$slug'
    | '/blog'
    | '/produits'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/blog/$slug'
    | '/produits/$slug'
    | '/blog/'
    | '/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
